---
- hosts: all
  become: ture

  tasks:
  - name: Stop current running container
    command: docker stop calculator
    ignore_errors: yes

  - name: Remove stopped containers
    command: docker rm calculator
    ignore_errors: yes

  - name: Remove docker image
    command: docker rmi chethanhms/calculatorImage
    ignore_errors: yes

  - name: Pull dockerImage from dockerhub
    command: docker pull chethanhms/calculatorImage
    
  - name: Create container using this image
    command: docker container run -d --name calculator -p 8080:8080 chethanhms/calculatorImage
