---
- hosts: web1
  #become: true 

  tasks:
  - name: building docker image
    command: "docker build -t calc-image ." 
    args:
      chdir: /opt/docker

  - name: add tag to the image
    command: docker tag calc-image athirac/calculatorimage

  - name: push image to dockerhub
    command: docker push athirac/calculatorimage

  - name: Remove image from ansible server
    command: docker rmi calc-image athirac/calculatorimage
    ignore_errors: yes
